/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Interfaz principal de la aplicación.
 * @author israelmedrano
 */
public class Principal extends javax.swing.JDialog {

    /**
     * Creates new form Principal
     */
    public Principal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Añado la foto y ajusto el tamaño
        ImageIcon imagen = new ImageIcon("src/imagenes/foto.png");
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(foto2.getWidth(), foto2.getHeight(), Image.SCALE_DEFAULT));
        foto2.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        foto2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        foto1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        altaCandidatosAdministracion = new javax.swing.JButton();
        ficheroAdministracion = new javax.swing.JButton();
        altaCandidatosAlmacen = new javax.swing.JButton();
        ficheroAlmacen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Amatic SC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROGRAMACIÓN JAVA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(903, Short.MAX_VALUE)
                .addComponent(foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setAlignmentX(5.0F);
        jPanel3.setAlignmentY(5.0F);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50));

        altaCandidatosAdministracion.setText("<html><center>Alta candidatos Administración</html>\n");
        altaCandidatosAdministracion.setToolTipText("");
        altaCandidatosAdministracion.setActionCommand("");
        altaCandidatosAdministracion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        altaCandidatosAdministracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        altaCandidatosAdministracion.setMaximumSize(new java.awt.Dimension(150, 150));
        altaCandidatosAdministracion.setMinimumSize(new java.awt.Dimension(150, 150));
        altaCandidatosAdministracion.setPreferredSize(new java.awt.Dimension(150, 150));
        altaCandidatosAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaCandidatosAdministracionActionPerformed(evt);
            }
        });
        jPanel3.add(altaCandidatosAdministracion);

        ficheroAdministracion.setText("<html><center>Listado \ncandidatos \nadministración\n(fichero de texto)</html>");
        ficheroAdministracion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        ficheroAdministracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ficheroAdministracion.setMaximumSize(new java.awt.Dimension(150, 150));
        ficheroAdministracion.setMinimumSize(new java.awt.Dimension(150, 150));
        ficheroAdministracion.setPreferredSize(new java.awt.Dimension(150, 150));
        ficheroAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficheroAdministracionActionPerformed(evt);
            }
        });
        jPanel3.add(ficheroAdministracion);

        altaCandidatosAlmacen.setText("<html><center>Alta candidatos Almacén");
        altaCandidatosAlmacen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        altaCandidatosAlmacen.setMaximumSize(new java.awt.Dimension(150, 150));
        altaCandidatosAlmacen.setMinimumSize(new java.awt.Dimension(150, 150));
        altaCandidatosAlmacen.setPreferredSize(new java.awt.Dimension(150, 150));
        altaCandidatosAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaCandidatosAlmacenActionPerformed(evt);
            }
        });
        jPanel3.add(altaCandidatosAlmacen);

        ficheroAlmacen.setText("<html><center>Listado candidatos almacén <br>(fichero de texto)");
        ficheroAlmacen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        ficheroAlmacen.setMaximumSize(new java.awt.Dimension(150, 150));
        ficheroAlmacen.setMinimumSize(new java.awt.Dimension(150, 150));
        ficheroAlmacen.setPreferredSize(new java.awt.Dimension(150, 150));
        ficheroAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficheroAlmacenActionPerformed(evt);
            }
        });
        jPanel3.add(ficheroAlmacen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ficheroAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficheroAlmacenActionPerformed
   try{ File archivo = new File("historicoAlmacen.txt");
    
    if(archivo.exists()){
        Desktop.getDesktop().open(archivo);
    }else{
        JOptionPane.showMessageDialog(null, "Archivo no encontrado");
    }
}
    catch(IOException e){
            e.printStackTrace();
            }
  
// TODO add your handling code here:
    }//GEN-LAST:event_ficheroAlmacenActionPerformed

    private void altaCandidatosAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaCandidatosAdministracionActionPerformed
this.dispose();
FormularioAdministracion F = new FormularioAdministracion(null, true);
F.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_altaCandidatosAdministracionActionPerformed

    private void altaCandidatosAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaCandidatosAlmacenActionPerformed
this.dispose();
FormularioAlmacen F= new FormularioAlmacen(null, true);
F.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_altaCandidatosAlmacenActionPerformed

    private void ficheroAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficheroAdministracionActionPerformed
try{ File archivo = new File("historicoAdministracion.txt");
    
    if(archivo.exists()){
        Desktop.getDesktop().open(archivo);
    }else{
        JOptionPane.showMessageDialog(null, "Archivo no encontrado");
    }
}
    catch(IOException e){
            e.printStackTrace();
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_ficheroAdministracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal dialog = new Principal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaCandidatosAdministracion;
    private javax.swing.JButton altaCandidatosAlmacen;
    private javax.swing.JButton ficheroAdministracion;
    private javax.swing.JButton ficheroAlmacen;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
